# Generated by Django 5.2 on 2025-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=20)),
                ("emp_name", models.CharField(max_length=100)),
                ("emp_email", models.EmailField(max_length=254)),
                ("emp_cont", models.CharField(max_length=20)),
            ],
        ),
    ]
